---
- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded

- name: daemon-reload
  command: systemctl daemon-reload
  changed_when: false
